version: "3"
services:
    fapp:
        container_name: test_flask_ngrok_ctr
        build: .
        image: test_flask_ngrok_images
        volumes:
            - ./www/:/var/www/
        environment:
            TZ: "Asia/Tokyo"
        stdin_open: true
        tty: true 
        ports:
            - 3031:3031
        command: uwsgi --ini /var/www/uwsgi.ini 